---
- name: Wait for EC2 setting up
  wait_for_connection:
    timeout: 60
- name: "update apt package"
  become: true
  apt:
    update_cache: yes

- name: "update package"
  become: true
  apt:
    upgrade: yes

- name: "remove dependencies no longer require"
  become: true
  apt:
    autoremove: yes

- name: "install nginx"
  become: true
  npm:
    name: nginx
    global: yes
    production: yes
    state: present
- name: copy index.html
  become: true
  shell: |
    echo "Hello world, my name is Tung" > /usr/share/nginx/html/
- name: Start nginx
  become: true
  service:
    name: nginx
    state: restarted