apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: udacityp5-deployment
spec:
  selector:
    matchLabels:
      app: udacityp5
  replicas: 1
  template:
    metadata:
      labels:
        app: udacityp5
    spec:
      containers:
      - name: udacityp5
        image: tungntvn/udacityp5
        ports:
        - containerPort: 80