version: 2.1
orbs:
  aws-eks: circleci/aws-eks@2.2.0
  aws-cli: circleci/aws-cli@3.1
  docker: circleci/docker@2.1.2
  kubernetes: circleci/kubernetes@1.3.1
jobs:         
  lint:
    docker:
    # Use the same Docker base as the project
    - image: python:3.7.3-stretch

    working_directory: ~/repo

    steps:
    - checkout
    - run:
        name: install dependencies
        command: |
          python3 -m venv venv
          . venv/bin/activate
          make install
          # Install hadolint
          wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
          chmod +x /bin/hadolint
    - save_cache:
        paths:
          - ./venv
        key: v1-dependencies-{{ checksum "requirements.txt" }}

    # run lint!
    - run:
        name: run lint
        command: |
          . venv/bin/activate
          make lint 
  build_image:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: tungntvn/udacityp5
          tag: latest
      - docker/push:
          image: tungntvn/udacityp5
          tag: latest
  build_infras:
    docker:
      - image: cimg/python:3.11.0
    steps:
      - checkout
      - aws-cli/setup
      - aws-eks/create-cluster:
          cluster-name: eks-udacityp5
          aws-region: $AWS_REGION
          node-type:  t2.micro
          nodes-min:  2
          nodes-max:  2
  deploy_application:
    docker:
      - image: cimg/python:3.11.0
    steps:
      - checkout
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: eks-udacityp5
          aws-region: ${AWS_REGION}
          install-kubectl: true
      - kubernetes/create-or-update-resource:
          resource-file-path: ".circleci/files/deployment.yml"
          resource-name: "deployment/udacityp5-deployment"
          get-rollout-status: true
          show-kubectl-command: true
      - kubernetes/create-or-update-resource:
          resource-file-path: ".circleci/files/service.yml"
          show-kubectl-command: true
      - run:
          name: Waiting for dns updated
          command: |
            sleep 5m

  smoke-test:
    docker:
      - image: cimg/python:3.11.0
    steps:
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: eks-udacityp5
          aws-region: ${AWS_REGION}
          install-kubectl: true
      - run:
          name: smoke test.
          command: |
            URL=$(kubectl describe services udacityp5 | grep "LoadBalancer Ingress" | awk '{print $3}')
            echo $URL
            if curl -s $URL | grep "Tung"
            then
                # Change this to 0 after the job fails
              exit 0
            else
              exit 1
            fi
workflows:
  default:
    jobs:
      - lint
      - build_infras:
          requires:
            - "lint"
      - build_image:
          requires:
            - "lint"
      - deploy_application:
          requires:
            - "build_image"
            - "build_infras"
      - smoke-test:
          requires:
            - "deploy_application"