version: 2.1
orbs:
  aws-eks: circleci/aws-eks@2.0.0
  kubernetes: circleci/kubernetes@0.3.0
  aws-cli: circleci/aws-cli@3.1
jobs:         
  build:
    docker:
    # Use the same Docker base as the project
    - image: python:3.7.3-stretch

    working_directory: ~/repo

    steps:
    - checkout
    - run:
        name: install dependencies
        command: |
          python3 -m venv venv
          . venv/bin/activate
          make install
          # Install hadolint
          wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
          chmod +x /bin/hadolint
    - save_cache:
        paths:
          - ./venv
        key: v1-dependencies-{{ checksum "requirements.txt" }}

    # run lint!
    - run:
        name: run lint
        command: |
          . venv/bin/activate
          make lint 
  build_infras:
    docker:
      - image: cimg/python:3.11.0
    steps:
      - checkout
      - aws-cli/setup
      - aws-eks/create-cluster:
          cluster-name: eks-udacity
          aws-region: $AWS_REGION
      

workflows:
  default:
    jobs:
      # - build
      - build_infras
